/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        surface: "#f9f9f9",
        "secondary-fixed": "#e3e2e2",
        "primary-container": "#1b365d",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c7c6c6",
        "surface-container": "#eeeeee",
        "surface-variant": "#e2e2e2",
        "secondary-container": "#e3e2e2",
        "on-tertiary-fixed-variant": "#623f0f",
        "inverse-surface": "#2f3131",
        "surface-bright": "#f9f9f9",
        error: "#ba1a1a",
        "on-secondary-fixed": "#1b1c1c",
        "tertiary-fixed-dim": "#f1bd81",
        "surface-container-highest": "#e2e2e2",
        "on-background": "#1a1c1c",
        "on-error": "#ffffff",
        "on-surface": "#1a1c1c",
        outline: "#74777f",
        "primary-fixed": "#d6e3ff",
        "surface-tint": "#465f88",
        background: "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        tertiary: "#321c00",
        "primary-fixed-dim": "#aec7f7",
        "inverse-on-surface": "#f1f1f1",
        "on-surface-variant": "#44474e",
        "on-primary": "#ffffff",
        primary: "#002046",
        "outline-variant": "#c4c6cf",
        "tertiary-fixed": "#ffddb9",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#2e476f",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001b3d",
        "inverse-primary": "#aec7f7",
        "on-secondary-container": "#646464",
        "on-tertiary-container": "#c6965e",
        "tertiary-container": "#4f2f00",
        "on-secondary-fixed-variant": "#464747",
        secondary: "#5e5e5e",
        "on-primary-container": "#87a0cd",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadada",
        "on-tertiary-fixed": "#2b1700",
        "surface-container-low": "#f4f3f3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        xs: "4px",
        base: "4px",
        gutter: "24px",
        lg: "24px",
        margin: "48px",
        xl: "32px",
        sm: "8px",
        "max-width": "1200px",
      },
      fontFamily: {
        "display-lg": ["IBM Plex Sans"],
        "headline-md": ["IBM Plex Sans"],
        "body-md": ["IBM Plex Sans"],
        "headline-lg": ["IBM Plex Sans"],
        "headline-lg-mobile": ["IBM Plex Sans"],
        "body-sm": ["IBM Plex Sans"],
        "label-md": ["IBM Plex Sans"],
        "headline-sm": ["IBM Plex Sans"],
        "label-sm": ["IBM Plex Sans"],
        "body-lg": ["IBM Plex Sans"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
