export const applications = [
  {
    id: "app-001",
    companyName: "Zurich Institute of Technology",
    department: "Department of Materials Science",
    role: "Graduate Research Assistant",
    roleSubtext: "Photovoltaics Project",
    dateApplied: "2024-10-12",
    status: "Under Review",
  },
  {
    id: "app-002",
    companyName: "NextGen Energy Corp",
    department: "R&D Division",
    role: "Summer Internship - Engineering",
    roleSubtext: "Req ID: 88291",
    dateApplied: "2024-10-05",
    status: "Interview",
  },
  {
    id: "app-003",
    companyName: "Global Health Initiative",
    department: "Data Analytics Team",
    role: "Data Analyst (Contract)",
    roleSubtext: "6-month term",
    dateApplied: "2024-09-28",
    status: "Applied",
  },
  {
    id: "app-004",
    companyName: "BioTech Innovations Ltd",
    department: "Lab Operations",
    role: "Junior Lab Technician",
    roleSubtext: "Full-time",
    dateApplied: "2024-09-15",
    status: "Shortlisted",
  },
  {
    id: "app-005",
    companyName: "Acme Software Solutions",
    department: "Frontend Team",
    role: "UI Developer",
    roleSubtext: "Remote",
    dateApplied: "2024-08-30",
    status: "Closed",
  },
];
