// Skills listed here should match names in SKILL_CATALOG (see skills.js) so the
// matching engine can compare them against a student's real skill profile —
// skills that don't exist in the catalog just always show up as "missing".
export const internships = [
  {
    id: "job-001",
    title: "Machine Learning Engineer Intern",
    company: "TechCorp AI Labs",
    type: "Internship",
    location: "Remote",
    skills: ["Python Programming", "Machine Learning", "Data Structures & Algorithms"],
    duration: "3 Months",
    stipend: "₹25,000 / Month",
    commitment: "Full-Time (40 hrs/week)",
    eligibility: [
      { label: "3rd year or above, B.Tech/B.E.", met: true },
      { label: "Remote-friendly", met: true },
    ],
    overview: [
      "Join TechCorp AI Labs' applied research team to build and evaluate machine learning models used in production recommendation systems.",
      "You'll work directly with senior ML engineers on data pipelines, model training, and evaluation — with real production impact by the end of the internship.",
    ],
    responsibilities: [
      "Build and iterate on ML models using Python and standard ML tooling.",
      "Analyze model performance and propose improvements backed by data.",
      "Collaborate with the data engineering team on pipeline reliability.",
    ],
    aboutCompany: "TechCorp AI Labs is a mid-size applied AI company building recommendation and personalization systems for e-commerce platforms.",
  },
  {
    id: "job-002",
    title: "Junior Backend Developer",
    company: "Global Systems Solutions",
    type: "Full-time",
    location: "Bangalore (Hybrid)",
    skills: ["SQL / Databases", "Git & Version Control", "Problem Solving"],
    duration: "Full-time role",
    stipend: "₹6,00,000 / Year CTC",
    commitment: "Full-Time (Hybrid, 3 days/week onsite)",
    eligibility: [
      { label: "Final year or recent graduate", met: true },
      { label: "Willing to relocate to Bangalore", met: false },
    ],
    overview: [
      "Global Systems Solutions is hiring junior backend developers to work on internal enterprise tooling used by Fortune 500 clients.",
      "You'll be mentored by senior engineers while owning small backend services end-to-end.",
    ],
    responsibilities: [
      "Design and maintain relational database schemas for internal services.",
      "Write clean, tested backend code and participate in code review.",
      "Work with product managers to scope and estimate small features.",
    ],
    aboutCompany: "Global Systems Solutions builds enterprise workflow software for logistics and manufacturing clients across Asia-Pacific.",
  },
  {
    id: "job-003",
    title: "Frontend Engineer Intern",
    company: "Creative Digital Agency",
    type: "Internship",
    location: "Mumbai",
    skills: ["JavaScript", "React", "Communication"],
    duration: "6 Months",
    stipend: "₹18,000 / Month",
    commitment: "Full-Time (40 hrs/week, onsite)",
    eligibility: [
      { label: "Portfolio of at least one React project", met: true },
      { label: "Onsite in Mumbai", met: true },
    ],
    overview: [
      "Creative Digital Agency builds marketing sites and web apps for consumer brands. As a frontend intern, you'll ship real client-facing UI.",
      "This role blends production React work with close collaboration alongside designers, so strong communication matters as much as code.",
    ],
    responsibilities: [
      "Implement responsive UI from Figma designs using React.",
      "Communicate progress and blockers directly with client-facing project leads.",
      "Participate in weekly design/dev sync to review in-progress work.",
    ],
    aboutCompany: "Creative Digital Agency is a 40-person studio delivering web experiences for consumer and D2C brands.",
  },
  {
    id: "job-004",
    title: "Full Stack Developer Intern",
    company: "Nexus Systems Institute",
    type: "Internship",
    location: "Remote",
    skills: ["JavaScript", "React", "SQL / Databases", "Git & Version Control"],
    duration: "4 Months",
    stipend: "₹20,000 / Month",
    commitment: "Full-Time (40 hrs/week)",
    eligibility: [
      { label: "2nd year or above", met: true },
      { label: "Remote-friendly", met: true },
    ],
    overview: [
      "Nexus Systems Institute is looking for a full stack intern to help build an internal research-collaboration platform end to end.",
      "You'll touch both the React frontend and the database-backed API layer, with direct mentorship from the founding engineering team.",
    ],
    responsibilities: [
      "Build features spanning the React frontend and the backend API/database layer.",
      "Write and review pull requests using Git workflows.",
      "Participate in sprint planning and daily standups.",
    ],
    aboutCompany: "Nexus Systems Institute builds collaboration tooling for university research labs.",
  },
  {
    id: "job-005",
    title: "Data Analyst Intern",
    company: "Global Health Initiative",
    type: "Internship",
    location: "Remote",
    skills: ["SQL / Databases", "Python Programming", "Problem Solving"],
    duration: "3 Months",
    stipend: "₹15,000 / Month",
    commitment: "Part-Time (20 hrs/week)",
    eligibility: [
      { label: "Coursework or project experience in statistics", met: true },
      { label: "Remote-friendly", met: true },
    ],
    overview: [
      "Global Health Initiative's data team analyzes public health datasets to inform policy recommendations across partner regions.",
      "As a data analyst intern, you'll write SQL queries, build small Python analysis scripts, and help produce reports for non-technical stakeholders.",
    ],
    responsibilities: [
      "Query and clean datasets using SQL and Python.",
      "Build summary reports and simple visualizations for program leads.",
      "Flag data quality issues and propose fixes.",
    ],
    aboutCompany: "Global Health Initiative is a non-profit working on public health data infrastructure across South Asia.",
  },
  {
    id: "job-006",
    title: "Cloud Infrastructure Intern",
    company: "Acme Software Solutions",
    type: "Internship",
    location: "Bangalore (Hybrid)",
    skills: ["Cloud Computing (AWS)", "Git & Version Control", "Problem Solving"],
    duration: "6 Months",
    stipend: "₹22,000 / Month",
    commitment: "Full-Time (40 hrs/week, hybrid)",
    eligibility: [
      { label: "3rd year or above, CSE/IT", met: true },
      { label: "Hybrid — Bangalore based", met: false },
    ],
    overview: [
      "Acme Software Solutions is hiring a cloud infrastructure intern to support their DevOps team as they migrate services to AWS.",
      "You'll get hands-on exposure to real production infrastructure, from CI/CD pipelines to cost optimization.",
    ],
    responsibilities: [
      "Assist in provisioning and monitoring AWS infrastructure.",
      "Support CI/CD pipeline maintenance and incident response drills.",
      "Document infrastructure changes for the wider engineering team.",
    ],
    aboutCompany: "Acme Software Solutions provides workflow automation software to mid-market logistics companies.",
  },
  {
    id: "job-007",
    title: "Materials Science Research Intern",
    company: "Zurich Institute of Technology — R&D Division",
    type: "Internship",
    location: "Zurich, Switzerland (Hybrid)",
    skills: ["Python Programming", "Problem Solving", "Communication"],
    duration: "6 Months (Starts Sept 2026)",
    stipend: "3,500 CHF / Month",
    commitment: "Full-Time (40 hrs/week)",
    eligibility: [
      { label: "Graduate or advanced undergraduate", met: true },
      { label: "Hybrid — Zurich based", met: false },
    ],
    overview: [
      "We are seeking a highly motivated graduate or advanced undergraduate student to join our core research team focusing on the optimization of semi-transparent photovoltaics for urban infrastructure. This role involves direct collaboration with industry partners to translate theoretical models into scalable, real-world applications.",
      "The successful candidate will assist in synthesizing novel polymer blends, conducting rigorous optical and electrical characterizations, and analyzing large datasets to identify performance bottlenecks. This internship provides unparalleled exposure to state-of-the-art laboratory facilities and a direct pathway to potential long-term commercial R&D roles.",
    ],
    responsibilities: [
      "Synthesize and characterize novel organic semiconductor materials.",
      "Fabricate and test thin-film photovoltaic devices under simulated urban conditions.",
      "Perform statistical analysis on device performance metrics using Python.",
      "Draft technical reports and present findings in weekly cross-functional meetings.",
    ],
    aboutCompany:
      "The Zurich Institute of Technology's R&D Division bridges the gap between academic materials science and commercial infrastructure deployment, specializing in sustainable urban technologies.",
  },
];
