// Skill Tests: per-skill, pass/fail MCQ exams — distinct from the self-rating
// survey in assessmentQuestions.js. Each question has ONE correct answer and
// scoring is objective (correct / total), not self-reported comfort level.
//
// passingScore is kept on the skill test definition (not hardcoded in the UI
// or scoring logic) so the threshold can be tuned per skill without touching
// component code — see skillTestService.js's scoreSkillTest().

export const SKILL_TESTS = [
  {
    id: "python",
    skillName: "Python Programming",
    title: "Python",
    category: "Technical Skill",
    durationMinutes: 15,
    passingScore: 70,
    questions: [
      {
        id: "py-1",
        prompt: "Which data structure stores key-value pairs?",
        options: [
          { value: "a", label: "List" },
          { value: "b", label: "Tuple" },
          { value: "c", label: "Dictionary" },
          { value: "d", label: "Set" },
        ],
        correctValue: "c",
      },
      {
        id: "py-2",
        prompt: "What does the len() function return for a string?",
        options: [
          { value: "a", label: "The memory address of the string" },
          { value: "b", label: "The number of characters in the string" },
          { value: "c", label: "The data type of the string" },
          { value: "d", label: "The last character of the string" },
        ],
        correctValue: "b",
      },
      {
        id: "py-3",
        prompt: "Which keyword is used to define a function in Python?",
        options: [
          { value: "a", label: "function" },
          { value: "b", label: "func" },
          { value: "c", label: "def" },
          { value: "d", label: "lambda" },
        ],
        correctValue: "c",
      },
      {
        id: "py-4",
        prompt: "What is the output of 3 // 2 in Python?",
        options: [
          { value: "a", label: "1.5" },
          { value: "b", label: "1" },
          { value: "c", label: "2" },
          { value: "d", label: "Error" },
        ],
        correctValue: "b",
      },
      {
        id: "py-5",
        prompt: "Which of these is a mutable data type?",
        options: [
          { value: "a", label: "Tuple" },
          { value: "b", label: "String" },
          { value: "c", label: "List" },
          { value: "d", label: "Integer" },
        ],
        correctValue: "c",
      },
      {
        id: "py-6",
        prompt: "What does the 'self' keyword refer to inside a class method?",
        options: [
          { value: "a", label: "The class itself" },
          { value: "b", label: "The current instance of the class" },
          { value: "c", label: "A global variable" },
          { value: "d", label: "The parent class" },
        ],
        correctValue: "b",
      },
      {
        id: "py-7",
        prompt: "Which module is used for regular expressions in Python?",
        options: [
          { value: "a", label: "regex" },
          { value: "b", label: "re" },
          { value: "c", label: "pyregex" },
          { value: "d", label: "string" },
        ],
        correctValue: "b",
      },
      {
        id: "py-8",
        prompt: "How do you handle exceptions in Python?",
        options: [
          { value: "a", label: "try / catch" },
          { value: "b", label: "try / except" },
          { value: "c", label: "catch / throw" },
          { value: "d", label: "error / handle" },
        ],
        correctValue: "b",
      },
      {
        id: "py-9",
        prompt: "What does 'list comprehension' let you do?",
        options: [
          { value: "a", label: "Sort a list in place" },
          { value: "b", label: "Build a new list concisely from an iterable" },
          { value: "c", label: "Convert a list to a dictionary" },
          { value: "d", label: "Delete duplicate values automatically" },
        ],
        correctValue: "b",
      },
      {
        id: "py-10",
        prompt: "Which of these correctly imports the 'pandas' library as 'pd'?",
        options: [
          { value: "a", label: "import pandas as pd" },
          { value: "b", label: "include pandas as pd" },
          { value: "c", label: "using pandas as pd" },
          { value: "d", label: "require pandas as pd" },
        ],
        correctValue: "a",
      },
    ],
  },
  {
    id: "sql",
    skillName: "SQL / Databases",
    title: "SQL",
    category: "Technical Skill",
    durationMinutes: 15,
    passingScore: 70,
    questions: [
      {
        id: "sql-1",
        prompt: "Which SQL statement is used to extract data from a database?",
        options: [
          { value: "a", label: "GET" },
          { value: "b", label: "SELECT" },
          { value: "c", label: "OPEN" },
          { value: "d", label: "EXTRACT" },
        ],
        correctValue: "b",
      },
      {
        id: "sql-2",
        prompt: "Which clause is used to filter rows in a SELECT query?",
        options: [
          { value: "a", label: "WHERE" },
          { value: "b", label: "FILTER" },
          { value: "c", label: "HAVING" },
          { value: "d", label: "LIMIT" },
        ],
        correctValue: "a",
      },
      {
        id: "sql-3",
        prompt: "Which JOIN returns only matching rows from both tables?",
        options: [
          { value: "a", label: "LEFT JOIN" },
          { value: "b", label: "RIGHT JOIN" },
          { value: "c", label: "INNER JOIN" },
          { value: "d", label: "FULL OUTER JOIN" },
        ],
        correctValue: "c",
      },
      {
        id: "sql-4",
        prompt: "Which keyword removes duplicate rows from a result set?",
        options: [
          { value: "a", label: "UNIQUE" },
          { value: "b", label: "DISTINCT" },
          { value: "c", label: "FILTER" },
          { value: "d", label: "NODUPE" },
        ],
        correctValue: "b",
      },
      {
        id: "sql-5",
        prompt: "Which statement is used to add new rows to a table?",
        options: [
          { value: "a", label: "INSERT INTO" },
          { value: "b", label: "ADD ROW" },
          { value: "c", label: "CREATE ROW" },
          { value: "d", label: "APPEND TO" },
        ],
        correctValue: "a",
      },
      {
        id: "sql-6",
        prompt: "What does a PRIMARY KEY constraint guarantee?",
        options: [
          { value: "a", label: "The column allows NULLs" },
          { value: "b", label: "The column values are unique and not null" },
          { value: "c", label: "The column is indexed for full-text search" },
          { value: "d", label: "The column auto-increments" },
        ],
        correctValue: "b",
      },
      {
        id: "sql-7",
        prompt: "Which clause groups rows sharing a value into summary rows?",
        options: [
          { value: "a", label: "GROUP BY" },
          { value: "b", label: "ORDER BY" },
          { value: "c", label: "PARTITION" },
          { value: "d", label: "COLLECT BY" },
        ],
        correctValue: "a",
      },
      {
        id: "sql-8",
        prompt: "Which function returns the number of rows matching a query?",
        options: [
          { value: "a", label: "SUM()" },
          { value: "b", label: "COUNT()" },
          { value: "c", label: "TOTAL()" },
          { value: "d", label: "ROWS()" },
        ],
        correctValue: "b",
      },
      {
        id: "sql-9",
        prompt: "Which statement permanently removes a table and its data?",
        options: [
          { value: "a", label: "DELETE TABLE" },
          { value: "b", label: "REMOVE TABLE" },
          { value: "c", label: "DROP TABLE" },
          { value: "d", label: "TRUNCATE ONLY" },
        ],
        correctValue: "c",
      },
      {
        id: "sql-10",
        prompt: "What is a foreign key used for?",
        options: [
          { value: "a", label: "Encrypting a column" },
          { value: "b", label: "Linking a row to a primary key in another table" },
          { value: "c", label: "Speeding up all queries automatically" },
          { value: "d", label: "Renaming a column" },
        ],
        correctValue: "b",
      },
    ],
  },
  {
    id: "communication",
    skillName: "Communication",
    title: "Communication",
    category: "Soft Skill",
    durationMinutes: 10,
    passingScore: 70,
    questions: [
      {
        id: "comm-1",
        prompt: "A teammate misunderstands your written instructions. What's the best first step?",
        options: [
          { value: "a", label: "Assume they weren't paying attention" },
          { value: "b", label: "Ask what part was unclear and rephrase it" },
          { value: "c", label: "Repeat the same message again" },
          { value: "d", label: "Escalate to a manager immediately" },
        ],
        correctValue: "b",
      },
      {
        id: "comm-2",
        prompt: "Active listening primarily involves:",
        options: [
          { value: "a", label: "Preparing your response while the other person talks" },
          { value: "b", label: "Fully focusing on and understanding the speaker before responding" },
          { value: "c", label: "Interrupting to show engagement" },
          { value: "d", label: "Only listening for keywords" },
        ],
        correctValue: "b",
      },
      {
        id: "comm-3",
        prompt: "In a status update to stakeholders, which is the most effective structure?",
        options: [
          { value: "a", label: "A long, unstructured narrative of everything that happened" },
          { value: "b", label: "Key outcomes first, then supporting details" },
          { value: "c", label: "Only raising problems, no progress" },
          { value: "d", label: "Technical jargon with no context" },
        ],
        correctValue: "b",
      },
      {
        id: "comm-4",
        prompt: "Giving constructive feedback is most effective when it is:",
        options: [
          { value: "a", label: "Vague but positive" },
          { value: "b", label: "Specific, behavior-focused, and actionable" },
          { value: "c", label: "Delivered publicly for accountability" },
          { value: "d", label: "Focused on personality traits" },
        ],
        correctValue: "b",
      },
      {
        id: "comm-5",
        prompt: "When emailing a busy stakeholder, you should:",
        options: [
          { value: "a", label: "Bury the ask at the end of a long email" },
          { value: "b", label: "Lead with a clear subject line and the ask up front" },
          { value: "c", label: "Avoid stating what you need" },
          { value: "d", label: "Use as much technical detail as possible" },
        ],
        correctValue: "b",
      },
      {
        id: "comm-6",
        prompt: "Nonverbal communication in a video call includes:",
        options: [
          { value: "a", label: "Only the words spoken" },
          { value: "b", label: "Tone of voice, eye contact, and body language" },
          { value: "c", label: "Font size in shared slides" },
          { value: "d", label: "Typing speed in chat" },
        ],
        correctValue: "b",
      },
      {
        id: "comm-7",
        prompt: "A disagreement arises in a team meeting. The best response is to:",
        options: [
          { value: "a", label: "Stay silent to avoid conflict" },
          { value: "b", label: "State your view respectfully and seek to understand others'" },
          { value: "c", label: "Insist you're right and move on" },
          { value: "d", label: "Bring it up privately with someone else later" },
        ],
        correctValue: "b",
      },
      {
        id: "comm-8",
        prompt: "When presenting to a non-technical audience, you should:",
        options: [
          { value: "a", label: "Use as much jargon as possible to sound credible" },
          { value: "b", label: "Translate technical concepts into plain, relevant terms" },
          { value: "c", label: "Skip context and jump straight to conclusions" },
          { value: "d", label: "Read the slides verbatim" },
        ],
        correctValue: "b",
      },
      {
        id: "comm-9",
        prompt: "Which is an example of a clarifying question?",
        options: [
          { value: "a", label: "\"That doesn't make sense.\"" },
          { value: "b", label: "\"When you say 'soon', do you mean this week or this month?\"" },
          { value: "c", label: "\"Whatever, I'll just guess.\"" },
          { value: "d", label: "\"I already know what you mean.\"" },
        ],
        correctValue: "b",
      },
      {
        id: "comm-10",
        prompt: "Written communication with a remote team benefits most from:",
        options: [
          { value: "a", label: "Being as brief as possible, even if unclear" },
          { value: "b", label: "Clarity and context, since tone can't be heard" },
          { value: "c", label: "Assuming shared context always exists" },
          { value: "d", label: "Avoiding questions to seem confident" },
        ],
        correctValue: "b",
      },
    ],
  },
  {
    id: "javascript",
    skillName: "JavaScript",
    title: "JavaScript",
    category: "Technical Skill",
    durationMinutes: 15,
    passingScore: 70,
    questions: [
      {
        id: "js-1",
        prompt: "Which keyword declares a block-scoped variable that can be reassigned?",
        options: [
          { value: "a", label: "var" },
          { value: "b", label: "let" },
          { value: "c", label: "const" },
          { value: "d", label: "static" },
        ],
        correctValue: "b",
      },
      {
        id: "js-2",
        prompt: "What does '===' check that '==' does not?",
        options: [
          { value: "a", label: "Variable scope" },
          { value: "b", label: "Type, in addition to value" },
          { value: "c", label: "Whether the variable is defined" },
          { value: "d", label: "Object reference equality only" },
        ],
        correctValue: "b",
      },
      {
        id: "js-3",
        prompt: "Which method adds an element to the end of an array?",
        options: [
          { value: "a", label: "array.push()" },
          { value: "b", label: "array.pop()" },
          { value: "c", label: "array.shift()" },
          { value: "d", label: "array.append()" },
        ],
        correctValue: "a",
      },
      {
        id: "js-4",
        prompt: "What is a closure in JavaScript?",
        options: [
          { value: "a", label: "A loop that never terminates" },
          { value: "b", label: "A function that remembers variables from its enclosing scope" },
          { value: "c", label: "A way to close a browser tab" },
          { value: "d", label: "A syntax error type" },
        ],
        correctValue: "b",
      },
      {
        id: "js-5",
        prompt: "Which of these correctly creates a Promise?",
        options: [
          { value: "a", label: "new Promise((resolve, reject) => {})" },
          { value: "b", label: "Promise.create()" },
          { value: "c", label: "async Promise()" },
          { value: "d", label: "Promise.new()" },
        ],
        correctValue: "a",
      },
      {
        id: "js-6",
        prompt: "What does the 'await' keyword do?",
        options: [
          { value: "a", label: "Declares a variable" },
          { value: "b", label: "Pauses execution until a Promise settles" },
          { value: "c", label: "Loops over an array" },
          { value: "d", label: "Imports a module" },
        ],
        correctValue: "b",
      },
      {
        id: "js-7",
        prompt: "Which array method transforms each element and returns a new array?",
        options: [
          { value: "a", label: "forEach()" },
          { value: "b", label: "map()" },
          { value: "c", label: "reduce()" },
          { value: "d", label: "filter()" },
        ],
        correctValue: "b",
      },
      {
        id: "js-8",
        prompt: "What does 'this' refer to inside a regular (non-arrow) object method?",
        options: [
          { value: "a", label: "The global window object always" },
          { value: "b", label: "The object the method was called on" },
          { value: "c", label: "The function itself" },
          { value: "d", label: "undefined, always" },
        ],
        correctValue: "b",
      },
      {
        id: "js-9",
        prompt: "Which is the correct way to destructure an object's 'name' property?",
        options: [
          { value: "a", label: "const [name] = obj;" },
          { value: "b", label: "const { name } = obj;" },
          { value: "c", label: "const name = obj->name;" },
          { value: "d", label: "const name := obj.name;" },
        ],
        correctValue: "b",
      },
      {
        id: "js-10",
        prompt: "What does JSON.stringify() do?",
        options: [
          { value: "a", label: "Parses a JSON string into an object" },
          { value: "b", label: "Converts a JavaScript value into a JSON string" },
          { value: "c", label: "Validates JSON syntax" },
          { value: "d", label: "Minifies JavaScript code" },
        ],
        correctValue: "b",
      },
    ],
  },
  {
    id: "react",
    skillName: "React",
    title: "React",
    category: "Technical Skill",
    durationMinutes: 15,
    passingScore: 70,
    questions: [
      {
        id: "react-1",
        prompt: "What hook lets a functional component hold local state?",
        options: [
          { value: "a", label: "useEffect" },
          { value: "b", label: "useState" },
          { value: "c", label: "useRef" },
          { value: "d", label: "useContext" },
        ],
        correctValue: "b",
      },
      {
        id: "react-2",
        prompt: "When does useEffect with an empty dependency array [] run?",
        options: [
          { value: "a", label: "On every render" },
          { value: "b", label: "Only once, after the initial render" },
          { value: "c", label: "Never" },
          { value: "d", label: "Only when the component unmounts" },
        ],
        correctValue: "b",
      },
      {
        id: "react-3",
        prompt: "What is JSX?",
        options: [
          { value: "a", label: "A CSS preprocessor" },
          { value: "b", label: "A syntax extension that lets you write HTML-like markup in JavaScript" },
          { value: "c", label: "A state management library" },
          { value: "d", label: "A build tool for React" },
        ],
        correctValue: "b",
      },
      {
        id: "react-4",
        prompt: "Why does React ask for a unique 'key' prop when rendering a list?",
        options: [
          { value: "a", label: "It's required for CSS styling" },
          { value: "b", label: "It helps React identify which items changed, added, or removed" },
          { value: "c", label: "It sets the element's HTML id attribute" },
          { value: "d", label: "It's optional and has no functional purpose" },
        ],
        correctValue: "b",
      },
      {
        id: "react-5",
        prompt: "How do you pass data from a parent component to a child component?",
        options: [
          { value: "a", label: "Through props" },
          { value: "b", label: "Through global variables only" },
          { value: "c", label: "Children cannot receive data" },
          { value: "d", label: "Through the DOM directly" },
        ],
        correctValue: "a",
      },
      {
        id: "react-6",
        prompt: "What does 'lifting state up' mean in React?",
        options: [
          { value: "a", label: "Moving state to a higher-level component so siblings can share it" },
          { value: "b", label: "Using useEffect to sync state with the server" },
          { value: "c", label: "Converting state into props permanently" },
          { value: "d", label: "Deleting unused state variables" },
        ],
        correctValue: "a",
      },
      {
        id: "react-7",
        prompt: "Which hook is used to access context values in a functional component?",
        options: [
          { value: "a", label: "useContext" },
          { value: "b", label: "useReducer" },
          { value: "c", label: "useMemo" },
          { value: "d", label: "useCallback" },
        ],
        correctValue: "a",
      },
      {
        id: "react-8",
        prompt: "What is the correct way to update state based on its previous value?",
        options: [
          { value: "a", label: "setCount(count + 1) always" },
          { value: "b", label: "setCount(prev => prev + 1)" },
          { value: "c", label: "count = count + 1" },
          { value: "d", label: "useState.update(count + 1)" },
        ],
        correctValue: "b",
      },
      {
        id: "react-9",
        prompt: "What is a controlled component in a React form?",
        options: [
          { value: "a", label: "A component whose form data is handled by React state" },
          { value: "b", label: "A component that cannot be re-rendered" },
          { value: "c", label: "A component styled with CSS modules" },
          { value: "d", label: "A component rendered only on the server" },
        ],
        correctValue: "a",
      },
      {
        id: "react-10",
        prompt: "What does React.memo() do?",
        options: [
          { value: "a", label: "Memoizes a component to skip re-rendering when props are unchanged" },
          { value: "b", label: "Stores data permanently in the browser" },
          { value: "c", label: "Converts a class component to a function component" },
          { value: "d", label: "Logs component render times to the console" },
        ],
        correctValue: "a",
      },
    ],
  },
  {
    id: "dsa",
    skillName: "Data Structures & Algorithms",
    title: "Data Structures & Algorithms",
    category: "Technical Skill",
    durationMinutes: 20,
    passingScore: 70,
    questions: [
      {
        id: "dsa-1",
        prompt: "What is the average time complexity of searching in a balanced binary search tree?",
        options: [
          { value: "a", label: "O(1)" },
          { value: "b", label: "O(log n)" },
          { value: "c", label: "O(n)" },
          { value: "d", label: "O(n^2)" },
        ],
        correctValue: "b",
      },
      {
        id: "dsa-2",
        prompt: "Which data structure uses LIFO (Last In, First Out) ordering?",
        options: [
          { value: "a", label: "Queue" },
          { value: "b", label: "Stack" },
          { value: "c", label: "Linked List" },
          { value: "d", label: "Heap" },
        ],
        correctValue: "b",
      },
      {
        id: "dsa-3",
        prompt: "What is the time complexity of accessing an element by index in an array?",
        options: [
          { value: "a", label: "O(1)" },
          { value: "b", label: "O(log n)" },
          { value: "c", label: "O(n)" },
          { value: "d", label: "O(n log n)" },
        ],
        correctValue: "a",
      },
      {
        id: "dsa-4",
        prompt: "Which sorting algorithm has the best average-case time complexity?",
        options: [
          { value: "a", label: "Bubble Sort — O(n^2)" },
          { value: "b", label: "Merge Sort — O(n log n)" },
          { value: "c", label: "Selection Sort — O(n^2)" },
          { value: "d", label: "Insertion Sort — O(n^2)" },
        ],
        correctValue: "b",
      },
      {
        id: "dsa-5",
        prompt: "What data structure is ideal for implementing a breadth-first search (BFS)?",
        options: [
          { value: "a", label: "Stack" },
          { value: "b", label: "Queue" },
          { value: "c", label: "Priority Heap" },
          { value: "d", label: "Trie" },
        ],
        correctValue: "b",
      },
      {
        id: "dsa-6",
        prompt: "What is a hash collision?",
        options: [
          { value: "a", label: "When two keys map to the same index in a hash table" },
          { value: "b", label: "When a hash table runs out of memory" },
          { value: "c", label: "When a key is deleted incorrectly" },
          { value: "d", label: "When a hash function returns a negative number" },
        ],
        correctValue: "a",
      },
      {
        id: "dsa-7",
        prompt: "Which traversal visits a binary tree's root, then left subtree, then right subtree?",
        options: [
          { value: "a", label: "In-order" },
          { value: "b", label: "Post-order" },
          { value: "c", label: "Pre-order" },
          { value: "d", label: "Level-order" },
        ],
        correctValue: "c",
      },
      {
        id: "dsa-8",
        prompt: "What is the space complexity of an algorithm that uses recursion with depth n and no other extra storage?",
        options: [
          { value: "a", label: "O(1)" },
          { value: "b", label: "O(n)" },
          { value: "c", label: "O(n^2)" },
          { value: "d", label: "O(log n)" },
        ],
        correctValue: "b",
      },
      {
        id: "dsa-9",
        prompt: "Which technique solves problems by breaking them into overlapping subproblems and caching results?",
        options: [
          { value: "a", label: "Greedy algorithms" },
          { value: "b", label: "Dynamic programming" },
          { value: "c", label: "Divide and conquer only" },
          { value: "d", label: "Brute force" },
        ],
        correctValue: "b",
      },
      {
        id: "dsa-10",
        prompt: "What is the worst-case time complexity of QuickSort?",
        options: [
          { value: "a", label: "O(n log n)" },
          { value: "b", label: "O(n)" },
          { value: "c", label: "O(n^2)" },
          { value: "d", label: "O(1)" },
        ],
        correctValue: "c",
      },
    ],
  },
  {
    id: "cloud-aws",
    skillName: "Cloud Computing (AWS)",
    title: "Cloud Computing (AWS)",
    category: "Technical Skill",
    durationMinutes: 15,
    passingScore: 70,
    questions: [
      {
        id: "aws-1",
        prompt: "Which AWS service provides scalable object storage?",
        options: [
          { value: "a", label: "EC2" },
          { value: "b", label: "S3" },
          { value: "c", label: "RDS" },
          { value: "d", label: "Lambda" },
        ],
        correctValue: "b",
      },
      {
        id: "aws-2",
        prompt: "What is Amazon EC2 primarily used for?",
        options: [
          { value: "a", label: "Serverless functions" },
          { value: "b", label: "Resizable virtual compute instances" },
          { value: "c", label: "Content delivery" },
          { value: "d", label: "DNS management" },
        ],
        correctValue: "b",
      },
      {
        id: "aws-3",
        prompt: "Which AWS service lets you run code without provisioning or managing servers?",
        options: [
          { value: "a", label: "Lambda" },
          { value: "b", label: "EC2" },
          { value: "c", label: "VPC" },
          { value: "d", label: "IAM" },
        ],
        correctValue: "a",
      },
      {
        id: "aws-4",
        prompt: "What does IAM manage in AWS?",
        options: [
          { value: "a", label: "Network bandwidth" },
          { value: "b", label: "Users, groups, roles, and permissions" },
          { value: "c", label: "Database backups" },
          { value: "d", label: "DNS routing" },
        ],
        correctValue: "b",
      },
      {
        id: "aws-5",
        prompt: "Which service is a managed relational database offering?",
        options: [
          { value: "a", label: "DynamoDB" },
          { value: "b", label: "RDS" },
          { value: "c", label: "S3" },
          { value: "d", label: "CloudFront" },
        ],
        correctValue: "b",
      },
      {
        id: "aws-6",
        prompt: "What is a VPC in AWS?",
        options: [
          { value: "a", label: "A virtual private network isolated within AWS" },
          { value: "b", label: "A billing dashboard" },
          { value: "c", label: "A type of storage bucket" },
          { value: "d", label: "A load balancer" },
        ],
        correctValue: "a",
      },
      {
        id: "aws-7",
        prompt: "Which AWS service is used for content delivery (CDN)?",
        options: [
          { value: "a", label: "CloudFront" },
          { value: "b", label: "CloudWatch" },
          { value: "c", label: "CloudTrail" },
          { value: "d", label: "CloudFormation" },
        ],
        correctValue: "a",
      },
      {
        id: "aws-8",
        prompt: "What does Auto Scaling do?",
        options: [
          { value: "a", label: "Automatically adjusts compute capacity based on demand" },
          { value: "b", label: "Automatically encrypts all S3 buckets" },
          { value: "c", label: "Automatically renews SSL certificates" },
          { value: "d", label: "Automatically deletes unused IAM users" },
        ],
        correctValue: "a",
      },
      {
        id: "aws-9",
        prompt: "Which pricing model charges only for the compute time your code actually runs?",
        options: [
          { value: "a", label: "Reserved Instances" },
          { value: "b", label: "On-Demand EC2" },
          { value: "c", label: "AWS Lambda pay-per-use" },
          { value: "d", label: "Spot Instances" },
        ],
        correctValue: "c",
      },
      {
        id: "aws-10",
        prompt: "What is the purpose of CloudWatch?",
        options: [
          { value: "a", label: "Monitoring and observability for AWS resources" },
          { value: "b", label: "Managing user identities" },
          { value: "c", label: "Hosting static websites" },
          { value: "d", label: "Running containers" },
        ],
        correctValue: "a",
      },
    ],
  },
  {
    id: "machine-learning",
    skillName: "Machine Learning",
    title: "Machine Learning",
    category: "Technical Skill",
    durationMinutes: 20,
    passingScore: 70,
    questions: [
      {
        id: "ml-1",
        prompt: "What is the main difference between supervised and unsupervised learning?",
        options: [
          { value: "a", label: "Supervised learning uses labeled data; unsupervised does not" },
          { value: "b", label: "Unsupervised learning is always more accurate" },
          { value: "c", label: "Supervised learning doesn't require any data" },
          { value: "d", label: "There is no difference" },
        ],
        correctValue: "a",
      },
      {
        id: "ml-2",
        prompt: "What does overfitting mean?",
        options: [
          { value: "a", label: "The model performs well on training data but poorly on new data" },
          { value: "b", label: "The model is too simple to capture patterns" },
          { value: "c", label: "The model trains too quickly" },
          { value: "d", label: "The model uses too little data" },
        ],
        correctValue: "a",
      },
      {
        id: "ml-3",
        prompt: "Which metric is commonly used to evaluate classification models?",
        options: [
          { value: "a", label: "Mean Squared Error" },
          { value: "b", label: "Accuracy / F1 Score" },
          { value: "c", label: "R-squared only" },
          { value: "d", label: "Standard deviation" },
        ],
        correctValue: "b",
      },
      {
        id: "ml-4",
        prompt: "What is the purpose of a train/test split?",
        options: [
          { value: "a", label: "To evaluate model performance on unseen data" },
          { value: "b", label: "To speed up training" },
          { value: "c", label: "To reduce the number of features" },
          { value: "d", label: "To visualize the data" },
        ],
        correctValue: "a",
      },
      {
        id: "ml-5",
        prompt: "Which algorithm is commonly used for linear regression problems?",
        options: [
          { value: "a", label: "K-Means Clustering" },
          { value: "b", label: "Ordinary Least Squares" },
          { value: "c", label: "Apriori Algorithm" },
          { value: "d", label: "Depth-First Search" },
        ],
        correctValue: "b",
      },
      {
        id: "ml-6",
        prompt: "What is regularization used for in machine learning?",
        options: [
          { value: "a", label: "To prevent overfitting by penalizing model complexity" },
          { value: "b", label: "To speed up data loading" },
          { value: "c", label: "To normalize output labels" },
          { value: "d", label: "To increase the learning rate" },
        ],
        correctValue: "a",
      },
      {
        id: "ml-7",
        prompt: "What does a confusion matrix show?",
        options: [
          { value: "a", label: "The correlation between all features" },
          { value: "b", label: "True/false positives and negatives for a classifier" },
          { value: "c", label: "The learning rate over time" },
          { value: "d", label: "The number of layers in a neural network" },
        ],
        correctValue: "b",
      },
      {
        id: "ml-8",
        prompt: "What is feature engineering?",
        options: [
          { value: "a", label: "Creating or transforming input variables to improve model performance" },
          { value: "b", label: "Designing the model's neural network architecture" },
          { value: "c", label: "Cleaning the training server's hardware" },
          { value: "d", label: "Writing unit tests for the model" },
        ],
        correctValue: "a",
      },
      {
        id: "ml-9",
        prompt: "Which of these is an unsupervised learning technique?",
        options: [
          { value: "a", label: "Linear Regression" },
          { value: "b", label: "K-Means Clustering" },
          { value: "c", label: "Logistic Regression" },
          { value: "d", label: "Decision Tree Classification" },
        ],
        correctValue: "b",
      },
      {
        id: "ml-10",
        prompt: "What is the purpose of cross-validation?",
        options: [
          { value: "a", label: "To get a more reliable estimate of model performance" },
          { value: "b", label: "To increase the size of the dataset" },
          { value: "c", label: "To automatically label unlabeled data" },
          { value: "d", label: "To deploy the model to production" },
        ],
        correctValue: "a",
      },
    ],
  },
  {
    id: "git-version-control",
    skillName: "Git & Version Control",
    title: "Git & Version Control",
    category: "Technical Skill",
    durationMinutes: 12,
    passingScore: 70,
    questions: [
      {
        id: "git-1",
        prompt: "Which command creates a new local branch and switches to it?",
        options: [
          { value: "a", label: "git branch -m" },
          { value: "b", label: "git checkout -b <name>" },
          { value: "c", label: "git switch --list" },
          { value: "d", label: "git clone -b" },
        ],
        correctValue: "b",
      },
      {
        id: "git-2",
        prompt: "What does 'git commit' do?",
        options: [
          { value: "a", label: "Uploads changes to a remote repository" },
          { value: "b", label: "Records staged changes to the local repository history" },
          { value: "c", label: "Deletes uncommitted changes" },
          { value: "d", label: "Creates a new repository" },
        ],
        correctValue: "b",
      },
      {
        id: "git-3",
        prompt: "What is the purpose of 'git pull'?",
        options: [
          { value: "a", label: "Fetches and merges changes from a remote branch" },
          { value: "b", label: "Pushes local commits to a remote" },
          { value: "c", label: "Deletes a remote branch" },
          { value: "d", label: "Creates a pull request" },
        ],
        correctValue: "a",
      },
      {
        id: "git-4",
        prompt: "What does a merge conflict indicate?",
        options: [
          { value: "a", label: "Git can't automatically reconcile changes to the same lines" },
          { value: "b", label: "The repository is corrupted" },
          { value: "c", label: "A commit message is missing" },
          { value: "d", label: "The remote repository is unreachable" },
        ],
        correctValue: "a",
      },
      {
        id: "git-5",
        prompt: "Which command stages a file for the next commit?",
        options: [
          { value: "a", label: "git stage" },
          { value: "b", label: "git add <file>" },
          { value: "c", label: "git commit <file>" },
          { value: "d", label: "git track <file>" },
        ],
        correctValue: "b",
      },
      {
        id: "git-6",
        prompt: "What is a '.gitignore' file used for?",
        options: [
          { value: "a", label: "Listing files/folders Git should not track" },
          { value: "b", label: "Storing commit messages" },
          { value: "c", label: "Listing collaborators" },
          { value: "d", label: "Configuring remote URLs" },
        ],
        correctValue: "a",
      },
      {
        id: "git-7",
        prompt: "What does 'git clone' do?",
        options: [
          { value: "a", label: "Creates a full local copy of a remote repository" },
          { value: "b", label: "Duplicates the current branch only" },
          { value: "c", label: "Merges two branches" },
          { value: "d", label: "Deletes the working directory" },
        ],
        correctValue: "a",
      },
      {
        id: "git-8",
        prompt: "What is the difference between 'git merge' and 'git rebase'?",
        options: [
          { value: "a", label: "There is no difference" },
          { value: "b", label: "Merge preserves history with a merge commit; rebase rewrites commit history onto a new base" },
          { value: "c", label: "Rebase only works on remote branches" },
          { value: "d", label: "Merge deletes the source branch automatically" },
        ],
        correctValue: "b",
      },
      {
        id: "git-9",
        prompt: "What does 'git status' show?",
        options: [
          { value: "a", label: "The commit history" },
          { value: "b", label: "The state of the working directory and staging area" },
          { value: "c", label: "The list of remote branches only" },
          { value: "d", label: "The current Git version" },
        ],
        correctValue: "b",
      },
      {
        id: "git-10",
        prompt: "What is a pull request typically used for?",
        options: [
          { value: "a", label: "Proposing and reviewing changes before merging into a branch" },
          { value: "b", label: "Downloading a repository" },
          { value: "c", label: "Deleting old commits" },
          { value: "d", label: "Renaming a repository" },
        ],
        correctValue: "a",
      },
    ],
  },
  {
    id: "teamwork",
    skillName: "Teamwork",
    title: "Teamwork",
    category: "Soft Skill",
    durationMinutes: 10,
    passingScore: 75,
    questions: [
      {
        id: "team-1",
        prompt: "A teammate disagrees with your approach during a project. What's the most constructive response?",
        options: [
          { value: "a", label: "Dismiss their concern and proceed as planned" },
          { value: "b", label: "Listen to their reasoning and discuss trade-offs openly" },
          { value: "c", label: "Avoid the conversation entirely" },
          { value: "d", label: "Escalate immediately without discussing" },
        ],
        correctValue: "b",
      },
      {
        id: "team-2",
        prompt: "What best describes effective delegation in a team?",
        options: [
          { value: "a", label: "Assigning tasks based on strengths and being clear about expectations" },
          { value: "b", label: "Giving every task to the most experienced person" },
          { value: "c", label: "Avoiding delegation to keep full control" },
          { value: "d", label: "Assigning tasks randomly to save time" },
        ],
        correctValue: "a",
      },
      {
        id: "team-3",
        prompt: "A team member consistently misses deadlines, affecting the group. What should you do first?",
        options: [
          { value: "a", label: "Publicly call them out in a team meeting" },
          { value: "b", label: "Have a private, direct conversation to understand the blocker" },
          { value: "c", label: "Redo their work without telling them" },
          { value: "d", label: "Ignore it and hope it improves" },
        ],
        correctValue: "b",
      },
      {
        id: "team-4",
        prompt: "What is psychological safety in a team context?",
        options: [
          { value: "a", label: "Feeling safe to take risks, voice ideas, and admit mistakes without fear" },
          { value: "b", label: "Having a strict hierarchy that avoids conflict" },
          { value: "c", label: "Physical safety in the workplace" },
          { value: "d", label: "Avoiding all disagreement" },
        ],
        correctValue: "a",
      },
      {
        id: "team-5",
        prompt: "During a group project, credit is unclear for a shared success. The best approach is to:",
        options: [
          { value: "a", label: "Claim the most credit for yourself" },
          { value: "b", label: "Acknowledge everyone's specific contributions" },
          { value: "c", label: "Avoid mentioning who did what" },
          { value: "d", label: "Let the manager decide without input" },
        ],
        correctValue: "b",
      },
      {
        id: "team-6",
        prompt: "What is the most effective way to give constructive feedback to a peer?",
        options: [
          { value: "a", label: "Be specific, focus on behavior/impact, and suggest improvement" },
          { value: "b", label: "Keep feedback vague to avoid discomfort" },
          { value: "c", label: "Only give feedback when asked, never proactively" },
          { value: "d", label: "Compare them unfavorably to other teammates" },
        ],
        correctValue: "a",
      },
      {
        id: "team-7",
        prompt: "In a cross-functional team, what helps most in reducing miscommunication?",
        options: [
          { value: "a", label: "Assuming everyone shares the same context" },
          { value: "b", label: "Regular, clear updates and shared documentation" },
          { value: "c", label: "Communicating only through informal chats" },
          { value: "d", label: "Minimizing all written communication" },
        ],
        correctValue: "b",
      },
      {
        id: "team-8",
        prompt: "How should conflicting priorities between team members typically be resolved?",
        options: [
          { value: "a", label: "Whoever is most senior always wins" },
          { value: "b", label: "Discuss trade-offs against shared goals and agree on priority" },
          { value: "c", label: "Avoid resolving it and let it stay ambiguous" },
          { value: "d", label: "Flip a coin" },
        ],
        correctValue: "b",
      },
      {
        id: "team-9",
        prompt: "What's a sign of a high-functioning team?",
        options: [
          { value: "a", label: "Everyone always agrees on everything" },
          { value: "b", label: "Members can disagree respectfully and still commit to decisions" },
          { value: "c", label: "One person makes all decisions" },
          { value: "d", label: "No one ever asks for help" },
        ],
        correctValue: "b",
      },
      {
        id: "team-10",
        prompt: "When onboarding a new team member, the most helpful thing is to:",
        options: [
          { value: "a", label: "Give them documentation and context, and check in regularly" },
          { value: "b", label: "Let them figure everything out alone" },
          { value: "c", label: "Assign them the hardest task immediately" },
          { value: "d", label: "Avoid introducing them to the team" },
        ],
        correctValue: "a",
      },
    ],
  },
  {
    id: "problem-solving",
    skillName: "Problem Solving",
    title: "Problem Solving",
    category: "Soft Skill",
    durationMinutes: 12,
    passingScore: 80,
    questions: [
      {
        id: "ps-1",
        prompt: "What is typically the first step in structured problem solving?",
        options: [
          { value: "a", label: "Jump straight to a solution" },
          { value: "b", label: "Clearly define and understand the problem" },
          { value: "c", label: "Ask someone else to solve it" },
          { value: "d", label: "Implement the most familiar solution" },
        ],
        correctValue: "b",
      },
      {
        id: "ps-2",
        prompt: "What does 'root cause analysis' aim to find?",
        options: [
          { value: "a", label: "The underlying cause of a problem, not just its symptoms" },
          { value: "b", label: "The most recent change made to a system" },
          { value: "c", label: "Who is responsible for the issue" },
          { value: "d", label: "A temporary workaround" },
        ],
        correctValue: "a",
      },
      {
        id: "ps-3",
        prompt: "When facing a complex problem, breaking it into smaller parts is called:",
        options: [
          { value: "a", label: "Decomposition" },
          { value: "b", label: "Escalation" },
          { value: "c", label: "Delegation" },
          { value: "d", label: "Abstraction only" },
        ],
        correctValue: "a",
      },
      {
        id: "ps-4",
        prompt: "You have limited data to make a decision. What's the best approach?",
        options: [
          { value: "a", label: "Wait indefinitely for complete data" },
          { value: "b", label: "Make a reasoned decision with available data, and adjust as new data arrives" },
          { value: "c", label: "Guess randomly" },
          { value: "d", label: "Avoid deciding at all" },
        ],
        correctValue: "b",
      },
      {
        id: "ps-5",
        prompt: "What is a trade-off analysis used for?",
        options: [
          { value: "a", label: "Comparing pros and cons of different solutions before deciding" },
          { value: "b", label: "Avoiding any decision-making" },
          { value: "c", label: "Selecting the cheapest option regardless of quality" },
          { value: "d", label: "Delaying a project indefinitely" },
        ],
        correctValue: "a",
      },
      {
        id: "ps-6",
        prompt: "A solution works but doesn't scale well. What should you consider?",
        options: [
          { value: "a", label: "Ignore scalability since it currently works" },
          { value: "b", label: "Evaluate whether to refactor now or plan for it later based on impact" },
          { value: "c", label: "Rewrite everything immediately without analysis" },
          { value: "d", label: "Blame the original design" },
        ],
        correctValue: "b",
      },
      {
        id: "ps-7",
        prompt: "What is the purpose of testing multiple hypotheses when debugging an issue?",
        options: [
          { value: "a", label: "To avoid fixing the wrong root cause based on assumption" },
          { value: "b", label: "To make the process take longer intentionally" },
          { value: "c", label: "It's unnecessary if the first guess seems reasonable" },
          { value: "d", label: "To assign blame more easily" },
        ],
        correctValue: "a",
      },
      {
        id: "ps-8",
        prompt: "What does it mean to 'fail fast' when solving a problem?",
        options: [
          { value: "a", label: "Give up quickly on any approach" },
          { value: "b", label: "Quickly test assumptions and identify what doesn't work early" },
          { value: "c", label: "Avoid experimentation entirely" },
          { value: "d", label: "Rush the final solution without validation" },
        ],
        correctValue: "b",
      },
      {
        id: "ps-9",
        prompt: "When multiple solutions seem viable, what's a good way to choose?",
        options: [
          { value: "a", label: "Pick the first idea that comes to mind" },
          { value: "b", label: "Evaluate each against clear criteria like cost, time, and impact" },
          { value: "c", label: "Choose based on personal preference only" },
          { value: "d", label: "Avoid choosing and implement all of them" },
        ],
        correctValue: "b",
      },
      {
        id: "ps-10",
        prompt: "After implementing a solution, what's an important next step?",
        options: [
          { value: "a", label: "Move on immediately without review" },
          { value: "b", label: "Evaluate the outcome and learn from what worked or didn't" },
          { value: "c", label: "Assume it's perfect and never revisit it" },
          { value: "d", label: "Delete all documentation about the process" },
        ],
        correctValue: "b",
      },
    ],
  },
  {
    id: "time-management",
    skillName: "Time Management",
    title: "Time Management",
    category: "Soft Skill",
    durationMinutes: 10,
    passingScore: 70,
    questions: [
      {
        id: "tm-1",
        prompt: "What does the Eisenhower Matrix help you prioritize by?",
        options: [
          { value: "a", label: "Urgency and importance" },
          { value: "b", label: "Alphabetical order" },
          { value: "c", label: "Who assigned the task" },
          { value: "d", label: "Task length only" },
        ],
        correctValue: "a",
      },
      {
        id: "tm-2",
        prompt: "You have five tasks due today but only time for three. What should you do?",
        options: [
          { value: "a", label: "Do them in the order they were assigned" },
          { value: "b", label: "Prioritize by impact/urgency and communicate about the rest" },
          { value: "c", label: "Try to rush all five and do a poor job on each" },
          { value: "d", label: "Skip all of them" },
        ],
        correctValue: "b",
      },
      {
        id: "tm-3",
        prompt: "What is 'time blocking'?",
        options: [
          { value: "a", label: "Scheduling specific blocks of time for specific tasks" },
          { value: "b", label: "Blocking calendar invites from coworkers" },
          { value: "c", label: "Working without any breaks" },
          { value: "d", label: "Ignoring deadlines" },
        ],
        correctValue: "a",
      },
      {
        id: "tm-4",
        prompt: "What is the main risk of multitasking on complex work?",
        options: [
          { value: "a", label: "It usually increases focus and speed" },
          { value: "b", label: "It often reduces quality and increases total time due to context-switching" },
          { value: "c", label: "It has no real downside" },
          { value: "d", label: "It only affects simple tasks" },
        ],
        correctValue: "b",
      },
      {
        id: "tm-5",
        prompt: "A deadline looks unachievable given the current scope. What's the best first step?",
        options: [
          { value: "a", label: "Say nothing and hope it works out" },
          { value: "b", label: "Communicate early with stakeholders about scope or timeline trade-offs" },
          { value: "c", label: "Silently drop lower-priority requirements without telling anyone" },
          { value: "d", label: "Wait until the deadline passes to mention it" },
        ],
        correctValue: "b",
      },
      {
        id: "tm-6",
        prompt: "What does the 80/20 (Pareto) principle suggest about productivity?",
        options: [
          { value: "a", label: "Roughly 80% of results often come from 20% of effort/tasks" },
          { value: "b", label: "You should work 80 hours a week" },
          { value: "c", label: "20% of tasks should be skipped entirely" },
          { value: "d", label: "It applies only to sales" },
        ],
        correctValue: "a",
      },
      {
        id: "tm-7",
        prompt: "What is a common cause of procrastination on large tasks?",
        options: [
          { value: "a", label: "The task feels overwhelming and isn't broken into smaller steps" },
          { value: "b", label: "The task is too easy" },
          { value: "c", label: "Having too much free time" },
          { value: "d", label: "Having too many resources available" },
        ],
        correctValue: "a",
      },
      {
        id: "tm-8",
        prompt: "What's an effective way to protect focus time from interruptions?",
        options: [
          { value: "a", label: "Leave notifications on for everything" },
          { value: "b", label: "Set clear blocks of uninterrupted time and communicate availability" },
          { value: "c", label: "Answer every message the moment it arrives" },
          { value: "d", label: "Avoid planning your day at all" },
        ],
        correctValue: "b",
      },
      {
        id: "tm-9",
        prompt: "Why is it useful to review your week's priorities in advance?",
        options: [
          { value: "a", label: "It helps align daily effort with what actually matters" },
          { value: "b", label: "It guarantees you'll finish everything" },
          { value: "c", label: "It's only useful for managers" },
          { value: "d", label: "It has no real benefit" },
        ],
        correctValue: "a",
      },
      {
        id: "tm-10",
        prompt: "What's the best response when unexpected urgent work disrupts your planned schedule?",
        options: [
          { value: "a", label: "Reassess priorities and adjust the plan rather than rigidly sticking to it" },
          { value: "b", label: "Ignore the urgent work entirely" },
          { value: "c", label: "Abandon all planning going forward" },
          { value: "d", label: "Do both the old and new plan simultaneously without adjusting" },
        ],
        correctValue: "a",
      },
    ],
  },
];

export function getSkillTestById(id) {
  return SKILL_TESTS.find((t) => t.id === id);
}
